BicicletaWEB/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using BicicletaWEB.Areas.HelpPage.ModelDescriptions;
using BicicletaWEB.Areas.HelpPage.Models;

namespace BicicletaWEB.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

BicicletaWEB/Controllers/VentaDetalles2Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BicicletaWEB.Models;

namespace BicicletaWEB.Controllers
{
    public class VentaDetalles2Controller : Controller
    {
        private Model1 db = new Model1();

        // GET: VentaDetalles2
        public ActionResult Index()
        {
            return View(db.VentaDetalles2.ToList());
        }

        // GET: VentaDetalles2/Details/5
        public ActionResult Details(int? id, int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalles2 ventaDetalles2 = db.VentaDetalles2.Find(id, id2);
            if (ventaDetalles2 == null)
            {
                return HttpNotFound();
            }
            return View(ventaDetalles2);
        }

        // GET: VentaDetalles2/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VentaDetalles2/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idVenta,idProducto,Cantidad")] VentaDetalles2 ventaDetalles2)
        {
            var ven = db.Productos.ToList();
            var producto = ven.Where(a => a.idProducto == ventaDetalles2.idProducto);
            bool hayProducto = producto.Any(n => n.Existencia >= ventaDetalles2.Cantidad);
            
            if (ModelState.IsValid && hayProducto)
            {
                producto.Select(a => a.Existencia -= ventaDetalles2.Cantidad).ToList();
                db.VentaDetalles2.Add(ventaDetalles2);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ventaDetalles2);
        }

        // GET: VentaDetalles2/Edit/5
        public ActionResult Edit(int? id, int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalles2 ventaDetalles2 = db.VentaDetalles2.Find(id, id2);
            if (ventaDetalles2 == null)
            {
                return HttpNotFound();
            }
            return View(ventaDetalles2);
        }

        // POST: VentaDetalles2/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idVenta,idProducto,Cantidad")] VentaDetalles2 ventaDetalles2)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ventaDetalles2).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ventaDetalles2);
        }

        // GET: VentaDetalles2/Delete/5
        public ActionResult Delete(int? id, int? id2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VentaDetalles2 ventaDetalles2 = db.VentaDetalles2.Find(id, id2);
            if (ventaDetalles2 == null)
            {
                return HttpNotFound();
            }
            return View(ventaDetalles2);
        }

        // POST: VentaDetalles2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id, int? id2)
        {
            VentaDetalles2 ventaDetalles2 = db.VentaDetalles2.Find(id, id2);
            db.VentaDetalles2.Remove(ventaDetalles2);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BicicletaWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Productos", "Index", "Productos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ventas", "Index", "Ventas", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Detalles Ventas", "Index", "VentaDetalles2", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>